"""Seed test documents for semantic search quality testing.

Each document targets a distinct topic. Probe phrases are designed so that
*no word* in the probe appears in the target document's title or content,
testing pure semantic retrieval via embedding similarity.
"""

import asyncio

import httpx

API = "http://localhost:8000"

DOCUMENTS = [
    {
        "title": "Endocrine Disorder Management Protocol",
        "content": (
            "ENDOCRINE DISORDER MANAGEMENT PROTOCOL\n\n"
            "Clinical Overview\n"
            "This protocol establishes standardized procedures for managing chronic "
            "metabolic conditions characterized by impaired insulin production and "
            "glucose regulation. The endocrine system's role in maintaining homeostasis "
            "requires careful monitoring of pancreatic function and cellular response "
            "to hormonal signals. Patients presenting with elevated fasting blood "
            "glucose levels above 126 mg/dL require immediate intervention according "
            "to the American Association of Clinical Endocrinologists guidelines.\n\n"
            "Diagnostic Criteria\n"
            "The diagnostic pathway begins with glycated hemoglobin measurements, "
            "which provide a three-month average of blood sugar levels. Values above "
            "6.5% on two separate occasions confirm the diagnosis. The oral glucose "
            "tolerance test remains the gold standard for detecting impaired glucose "
            "tolerance, where patients ingest 75 grams of glucose and blood levels "
            "are measured at two-hour intervals. Fasting plasma glucose testing should "
            "be conducted after an eight-hour fast for accurate baseline readings.\n\n"
            "Pharmacological Interventions\n"
            "First-line treatment typically begins with metformin hydrochloride, which "
            "reduces hepatic glucose production and improves peripheral insulin "
            "sensitivity. The standard titration schedule starts at 500mg daily and "
            "increases to a maximum of 2000mg over several weeks to minimize "
            "gastrointestinal side effects. For patients who do not achieve target "
            "HbA1c levels with monotherapy, sulfonylureas such as glimepiride "
            "stimulate pancreatic beta cells to increase endogenous insulin secretion.\n\n"
            "Advanced therapeutic options include GLP-1 receptor agonists like "
            "semaglutide and liraglutide, which slow gastric emptying and promote "
            "satiety while enhancing glucose-dependent insulin release. SGLT2 "
            "inhibitors represent a newer class that promotes urinary glucose excretion "
            "and has demonstrated cardiovascular and renal protective benefits in "
            "multiple randomized controlled trials. DPP-4 inhibitors such as "
            "sitagliptin provide modest HbA1c reduction with a favorable side effect "
            "profile.\n\n"
            "Lifestyle Modification Requirements\n"
            "Medical nutrition therapy requires patients to work with registered "
            "dietitians to develop individualized meal plans focusing on carbohydrate "
            "counting and glycemic index awareness. The recommended macronutrient "
            "distribution includes 45-60% of calories from carbohydrates, 15-20% "
            "from protein, and 20-35% from fats, with saturated fat limited to less "
            "than 7% of total calories. Physical activity prescriptions should target "
            "a minimum of 150 minutes per week of moderate-intensity aerobic exercise "
            "combined with resistance training twice weekly.\n\n"
            "Monitoring and Follow-Up\n"
            "Quarterly HbA1c testing is recommended for patients not meeting treatment "
            "goals, while those with stable control may be tested semiannually. "
            "Self-monitoring of blood glucose should be performed at varying "
            "frequencies depending on the treatment regimen, with patients on "
            "intensive insulin therapy checking four to seven times daily. Annual "
            "comprehensive foot examinations, dilated eye examinations, and urine "
            "microalbumin testing are essential components of preventive care.\n\n"
            "Complication Surveillance\n"
            "Long-term metabolic dysregulation can lead to microvascular complications "
            "including retinopathy, nephropathy, and peripheral neuropathy. "
            "Macrovascular complications such as coronary artery disease, "
            "cerebrovascular disease, and peripheral arterial disease require "
            "aggressive risk factor modification. The UK Prospective Diabetes Study "
            "demonstrated that each 1% reduction in HbA1c correlates with a 37% "
            "decrease in microvascular complications and a 21% reduction in "
            "diabetes-related mortality.\n\n"
            "Patient Education Framework\n"
            "Structured education programs should cover hypoglycemia recognition and "
            "management, sick day rules, proper foot care techniques, and the "
            "importance of medication adherence. Carbohydrate counting education "
            "enables patients to match prandial insulin doses to meal content, "
            "improving postprandial glucose excursions. Psychosocial assessment "
            "should screen for diabetes distress, which affects approximately 36% "
            "of patients and negatively impacts self-management behaviors.\n\n"
            "Technology Integration\n"
            "Continuous glucose monitoring systems provide real-time interstitial "
            "glucose readings every five minutes, allowing patients and providers "
            "to identify glycemic patterns and trends. Insulin pump therapy, "
            "including hybrid closed-loop systems, automates basal insulin delivery "
            "and can reduce HbA1c by an additional 0.5-1.0% compared to multiple "
            "daily injections. Telemedicine platforms facilitate remote monitoring "
            "and medication adjustments, particularly beneficial for patients in "
            "rural or underserved areas.\n\n"
            "Population Health Considerations\n"
            "Disparities in outcomes persist across socioeconomic and racial groups, "
            "necessitating culturally tailored interventions. Community health worker "
            "programs have demonstrated effectiveness in improving glycemic control "
            "among underserved populations. Insurance coverage for diabetes "
            "self-management education and medical nutrition therapy varies "
            "significantly by state and payer type, creating barriers to "
            "comprehensive care delivery."
        ),
        "probe": "hyperglycemia ketoacidosis diabetic",
    },
    {
        "title": "Intangible Asset Protection Framework",
        "content": (
            "INTANGIBLE ASSET PROTECTION FRAMEWORK\n\n"
            "Introduction\n"
            "This document outlines the comprehensive legal framework for protecting "
            "creations of the mind, including inventions, literary and artistic works, "
            "designs, symbols, names, and images used in commerce. The modern knowledge "
            "economy depends on robust legal mechanisms that grant creators exclusive "
            "rights over their intangible assets for limited periods, balancing "
            "innovation incentives with public access to knowledge.\n\n"
            "Patent Law Fundamentals\n"
            "Patent protection grants inventors the right to exclude others from "
            "making, using, selling, or importing their invention for a period of "
            "twenty years from the filing date. To qualify for patentability, an "
            "invention must demonstrate novelty, non-obviousness to a person skilled "
            "in the relevant art, and practical utility. The specification must enable "
            "a person of ordinary skill to make and use the invention without undue "
            "experimentation, while claims define the precise legal boundaries of the "
            "protected subject matter.\n\n"
            "The America Invents Act of 2011 transitioned the United States from a "
            "first-to-invent to a first-inventor-to-file system, harmonizing with "
            "international norms. Provisional applications provide a twelve-month "
            "window to assess commercial viability before filing a non-provisional "
            "application, establishing an early priority date at lower cost. Patent "
            "Cooperation Treaty filings streamline international protection by "
            "allowing a single application to serve as a placeholder in over 150 "
            "member countries.\n\n"
            "Copyright Protection Scope\n"
            "Copyright subsists in original works of authorship fixed in any tangible "
            "medium of expression, including literary works, musical compositions, "
            "dramatic works, choreography, pictorial and graphic works, motion "
            "pictures, sound recordings, and architectural works. Protection attaches "
            "automatically upon fixation without requiring registration, though "
            "registration with the Copyright Office provides significant procedural "
            "advantages including the ability to seek statutory damages and "
            "attorney's fees in infringement actions.\n\n"
            "The duration of copyright protection for works created after January 1, "
            "1978 extends for the life of the author plus seventy years. For works "
            "made for hire, anonymous works, and pseudonymous works, protection lasts "
            "for ninety-five years from publication or 120 years from creation, "
            "whichever expires first. The fair use doctrine permits limited use of "
            "copyrighted material without permission for purposes such as criticism, "
            "comment, news reporting, teaching, scholarship, and research, evaluated "
            "through a four-factor balancing test.\n\n"
            "Trademark and Trade Dress\n"
            "Trademark law protects words, phrases, symbols, designs, or combinations "
            "thereof that identify and distinguish the source of goods or services. "
            "Rights arise through actual use in commerce, though federal registration "
            "on the Principal Register provides constructive nationwide notice, prima "
            "facie evidence of validity, and the potential for incontestability after "
            "five years of continuous use. The Lanham Act prohibits registration of "
            "marks that are merely descriptive, generic, deceptive, or likely to "
            "cause confusion with existing marks.\n\n"
            "Trade dress protection extends to the overall visual appearance and "
            "packaging of a product that serves as a source identifier. To establish "
            "infringement under Section 43(a) of the Lanham Act, plaintiffs must "
            "demonstrate that the trade dress is non-functional, inherently "
            "distinctive or has acquired secondary meaning, and that the defendant's "
            "use creates a likelihood of confusion among reasonable consumers.\n\n"
            "Trade Secret Protection\n"
            "Trade secret law protects confidential business information that derives "
            "independent economic value from not being generally known and is subject "
            "to reasonable efforts to maintain its secrecy. The Defend Trade Secrets "
            "Act of 2016 created a federal civil cause of action for trade secret "
            "misappropriation, supplementing the existing patchwork of state laws "
            "largely based on the Uniform Trade Secrets Act. Remedies include "
            "injunctive relief, damages for actual loss and unjust enrichment, "
            "exemplary damages for willful misappropriation, and attorney's fees in "
            "cases of bad faith.\n\n"
            "Reasonable secrecy measures may include non-disclosure agreements, "
            "access controls, encryption, employee training programs, and physical "
            "security protocols. The inevitable disclosure doctrine, recognized in "
            "some jurisdictions, permits courts to enjoin a former employee from "
            "working for a competitor where the employee's new position would "
            "inevitably result in disclosure of trade secrets, even absent evidence "
            "of actual misappropriation.\n\n"
            "International Harmonization\n"
            "The Agreement on Trade-Related Aspects of Intellectual Property Rights "
            "establishes minimum standards for IP protection among World Trade "
            "Organization members. The Madrid Protocol simplifies international "
            "trademark registration through a centralized filing system administered "
            "by the World Intellectual Property Organization. The Berne Convention "
            "for the Protection of Literary and Artistic Works mandates automatic "
            "copyright protection without formalities and establishes the principle "
            "of national treatment.\n\n"
            "Enforcement Mechanisms\n"
            "Rights holders may pursue remedies through federal district courts, the "
            "International Trade Commission for import-related infringement, and "
            "alternative dispute resolution including arbitration and mediation. "
            "Cease and desist letters serve as a preliminary enforcement tool, often "
            "resolving disputes without litigation. Digital Millennium Copyright Act "
            "takedown notices provide an administrative mechanism for removing "
            "infringing content from online platforms, though counter-notification "
            "procedures protect against abusive claims."
        ),
        "probe": "pirated counterfeit plagiarized",
    },
    {
        "title": "Real Property Assessment Methodology",
        "content": (
            "REAL PROPERTY ASSESSMENT METHODOLOGY\n\n"
            "Fundamental Principles\n"
            "Property valuation represents the systematic process of estimating the "
            "market worth of land and improvements at a specific point in time. The "
            "concept of highest and best use underpins all valuation approaches, "
            "requiring the appraiser to determine the legally permissible, physically "
            "possible, financially feasible, and maximally productive use of the "
            "subject property. Market value assumes a willing buyer and seller, both "
            "acting with reasonable knowledge and without undue pressure, in an "
            "arms-length transaction conducted with typical marketing exposure.\n\n"
            "The principle of substitution states that a rational purchaser will pay "
            "no more for a property than the cost of acquiring an equally desirable "
            "substitute. Conformity suggests that maximum value is achieved when "
            "properties within a neighborhood maintain reasonable similarity in use, "
            "size, and quality. The principle of anticipation recognizes that value "
            "is created by the expectation of future benefits, whether through "
            "income generation, appreciation, or utility.\n\n"
            "Sales Comparison Approach\n"
            "The sales comparison approach derives value by analyzing recent "
            "transactions of comparable properties and adjusting for differences in "
            "physical characteristics, location, transaction conditions, and market "
            "conditions at the time of sale. Adjustments are applied to the "
            "comparable sales, not the subject property, and may be expressed as "
            "dollar amounts or percentages. An appraiser typically selects three to "
            "five comparable sales that required the fewest adjustments, as excessive "
            "adjustments reduce the reliability of the analysis.\n\n"
            "Location adjustments account for differences in neighborhood quality, "
            "proximity to amenities, school district boundaries, traffic patterns, "
            "and environmental factors such as flood zones or airport noise contours. "
            "Physical adjustments address variations in gross living area, lot size, "
            "bedroom and bathroom count, quality of construction, condition, "
            "functional utility, and presence of features such as fireplaces, pools, "
            "or views. Market conditions adjustments reflect changes in price levels "
            "between the comparable sale date and the effective valuation date.\n\n"
            "Income Capitalization Approach\n"
            "The income approach converts anticipated future income streams into a "
            "present value estimate, reflecting the investment decision-making "
            "process of market participants. Direct capitalization applies an overall "
            "capitalization rate derived from market data to a single year's "
            "stabilized net operating income. The capitalization rate represents the "
            "relationship between income and value and is extracted from comparable "
            "sales by dividing the property's net operating income by its sale price.\n\n"
            "Discounted cash flow analysis projects income and expenses over a "
            "multi-year holding period, applying a terminal capitalization rate to "
            "the final year's income to estimate reversion value. Cash flows and the "
            "reversion are discounted to present value using a discount rate that "
            "reflects the investor's required rate of return given the risk profile "
            "of the investment. Lease-by-lease analysis models each tenant's "
            "contractual rent, expense reimbursements, renewal probability, and "
            "downtime between tenancies for multi-tenant commercial properties.\n\n"
            "Cost Approach\n"
            "The cost approach estimates value as the land value plus the depreciated "
            "cost of improvements. Land value is typically derived through the sales "
            "comparison approach applied to vacant land parcels. Replacement cost new "
            "represents the expenditure required to construct a substitute improvement "
            "of equivalent utility using modern materials and methods, while "
            "reproduction cost new estimates the cost of constructing an exact "
            "replica.\n\n"
            "Depreciation is categorized into three forms: physical deterioration "
            "resulting from wear and tear and deferred maintenance, functional "
            "obsolescence caused by design deficiencies or super-adequacies relative "
            "to market standards, and external obsolescence arising from factors "
            "outside the property boundaries such as neighborhood decline or changes "
            "in zoning regulations. Accrued depreciation is measured through the "
            "age-life method, the breakdown method, or market extraction from "
            "comparable sales data.\n\n"
            "Special Purpose Properties\n"
            "Valuation of special purpose properties such as hospitals, schools, "
            "churches, and government buildings presents unique challenges due to "
            "limited market transaction data. These properties are typically valued "
            "using the cost approach as the primary method, supplemented by the "
            "income approach where the property generates revenue. Going concern "
            "value, which includes both real property and business enterprise value, "
            "must be distinguished from real property value for ad valorem taxation "
            "purposes.\n\n"
            "Mass Appraisal Systems\n"
            "Computer-assisted mass appraisal systems employ statistical modeling to "
            "value large portfolios of properties efficiently for property tax "
            "assessment purposes. Multiple regression analysis identifies the "
            "contribution of individual property characteristics to overall value, "
            "generating valuation equations applied uniformly across the assessment "
            "jurisdiction. Geographic information systems enable spatial analysis of "
            "value patterns and market trends, supporting ratio studies that evaluate "
            "assessment uniformity and equity.\n\n"
            "Regulatory Framework\n"
            "The Uniform Standards of Professional Appraisal Practice establish "
            "ethical and performance standards for appraisers in the United States. "
            "Financial Institutions Reform, Recovery, and Enforcement Act of 1989 "
            "mandates state licensing and certification of appraisers performing "
            "valuations for federally related transactions. International Valuation "
            "Standards promote consistency in valuation practice across national "
            "boundaries, facilitating cross-border investment and financial reporting."
        ),
        "probe": "mortgage loan homeowner",
    },
    {
        "title": "Distributed Computing Infrastructure Design",
        "content": (
            "DISTRIBUTED COMPUTING INFRASTRUCTURE DESIGN\n\n"
            "Architectural Overview\n"
            "Modern distributed computing environments leverage virtualized resource "
            "pools delivered over public networks as metered services, enabling "
            "organizations to replace upfront capital expenditure with variable "
            "operational expenditure. The shared responsibility model delineates "
            "security obligations between the service provider, responsible for "
            "security of the infrastructure, and the customer, responsible for "
            "security within the infrastructure including data classification, "
            "identity management, and application-level controls.\n\n"
            "Infrastructure as a Service provides virtualized compute, storage, and "
            "networking resources that customers provision and manage through "
            "self-service portals and programmatic interfaces. Platform as a Service "
            "abstracts the underlying infrastructure, providing managed runtime "
            "environments for application deployment without requiring customers to "
            "manage operating systems or middleware. Software as a Service delivers "
            "fully managed applications accessible through web browsers or APIs, "
            "eliminating customer responsibility for any infrastructure management.\n\n"
            "Compute Virtualization and Containerization\n"
            "Hypervisor technology enables multiple virtual machines to share "
            "physical host resources through hardware-assisted virtualization "
            "extensions found in modern processors. Type 1 hypervisors run directly "
            "on hardware without an intervening operating system, providing superior "
            "performance isolation compared to Type 2 hypervisors that operate as "
            "applications within a host operating system. Live migration capabilities "
            "allow running virtual machines to be transferred between physical hosts "
            "without service interruption, facilitating maintenance and load "
            "balancing.\n\n"
            "Containerization represents an operating-system-level virtualization "
            "approach that packages applications with their dependencies into "
            "isolated user-space instances sharing the host kernel. Unlike virtual "
            "machines, containers do not require a full guest operating system, "
            "resulting in significantly lower overhead and faster startup times "
            "measured in seconds rather than minutes. Orchestration platforms "
            "automate container deployment, scaling, and management across clusters "
            "of hosts, handling service discovery, load distribution, health "
            "monitoring, and rolling updates.\n\n"
            "Storage Architectures\n"
            "Object storage provides highly scalable, eventually consistent storage "
            "for unstructured data accessed through RESTful APIs, with each object "
            "containing data, metadata, and a unique identifier. Unlike traditional "
            "file systems, object storage employs a flat namespace rather than "
            "hierarchical directory structures, enabling horizontal scaling across "
            "distributed nodes. Block storage presents raw storage volumes that can "
            "be attached to virtual machines as persistent disks, supporting random "
            "read-write access patterns required by databases and transactional "
            "workloads.\n\n"
            "Content delivery networks cache static and dynamic content at edge "
            "locations geographically distributed near end users, reducing latency "
            "and origin server load. Replication strategies including synchronous "
            "and asynchronous mirroring ensure data durability and availability "
            "across multiple availability zones within a geographic region. Storage "
            "tiering policies automatically transition data between "
            "performance-optimized and cost-optimized storage classes based on "
            "access patterns and lifecycle rules.\n\n"
            "Networking and Security\n"
            "Virtual private networks establish encrypted tunnels between on-premises "
            "data centers and virtualized environments, enabling hybrid architectures "
            "that span private and public infrastructure. Software-defined networking "
            "decouples the control plane from the data plane, allowing network "
            "topology and policies to be managed programmatically through APIs "
            "rather than individual device configuration. Security groups and network "
            "access control lists provide stateful and stateless packet filtering at "
            "the instance and subnet boundaries respectively.\n\n"
            "Identity and access management systems enforce the principle of least "
            "privilege through role-based access controls, with temporary credentials "
            "generated through token services reducing the risk of long-lived "
            "credential compromise. Encryption protects data at rest using "
            "server-side mechanisms with provider-managed or customer-managed keys, "
            "and data in transit using Transport Layer Security protocols. API "
            "gateway services provide a single entry point for client requests, "
            "handling authentication, rate limiting, request transformation, and "
            "response caching.\n\n"
            "Scalability and Resilience\n"
            "Horizontal scaling adds additional compute instances behind load "
            "balancers that distribute incoming traffic based on configurable "
            "algorithms including round-robin, least connections, and weighted "
            "distribution. Auto-scaling policies dynamically adjust instance counts "
            "based on observed metrics such as CPU utilization, request latency, or "
            "custom application metrics published through monitoring services. "
            "Stateless application design, where session data is externalized to "
            "distributed caches or databases, enables any instance to serve any "
            "request without affinity requirements.\n\n"
            "Multi-region architectures replicate application stacks across "
            "geographically separated facilities to survive regional failures, with "
            "global load balancing routing users to the nearest healthy region. "
            "Chaos engineering practices deliberately inject failures into production "
            "systems to validate resilience assumptions and identify unexpected "
            "failure modes before they manifest during actual incidents. Circuit "
            "breaker patterns prevent cascading failures by detecting unresponsive "
            "downstream services and failing fast rather than accumulating queued "
            "requests.\n\n"
            "Observability and Operations\n"
            "Distributed tracing follows requests across service boundaries by "
            "propagating correlation identifiers, enabling latency analysis and "
            "bottleneck identification in microservice architectures. Centralized "
            "logging aggregates structured log events from all components into "
            "searchable indexes with retention policies balancing operational needs "
            "against storage costs. Metrics collection at one-minute granularity "
            "feeds dashboards and alerting systems that notify operators of threshold "
            "violations through multiple notification channels including email, "
            "messaging platforms, and automated incident response integrations."
        ),
        "probe": "docker kubernetes serverless",
    },
]


async def main() -> None:
    async with httpx.AsyncClient(base_url=API, timeout=30) as client:
        # find or create a client to own the documents
        lookup = await client.get("/v1/clients/lookup", params={"email": "test@metadata.com"})
        if lookup.status_code == 200:
            owner_id = lookup.json()["id"]
            print(f"Using existing client: {owner_id}")
        else:
            create = await client.post(
                "/v1/clients",
                json={
                    "first_name": "Test",
                    "last_name": "User",
                    "email": "test@metadata.com",
                    "description": "Test client for seeded documents",
                },
            )
            if create.status_code not in (201, 409):
                print(f"Failed to create client: {create.status_code} {create.text}")
                return
            owner_id = create.json().get("id") or (
                await client.get("/v1/clients/lookup", params={"email": "test@metadata.com"})
            ).json()["id"]
            print(f"Created client: {owner_id}")

        for doc in DOCUMENTS:
            resp = await client.post(
                f"/v1/clients/{owner_id}/documents",
                json={"title": doc["title"], "content": doc["content"]},
            )
            if resp.status_code == 201:
                body = resp.json()
                print(f"  Created: {doc['title']} (id={body['id']})")
                print(f"    Probe: '{doc['probe']}' — 0 words in target document")
            else:
                print(f"  FAILED: {doc['title']} — {resp.status_code} {resp.text[:120]}")


if __name__ == "__main__":
    asyncio.run(main())
